### ISSUE TITLE
RangeError

### ISSUE THREAD

**Issue by leodutra** [BridgeAR/safe-stable-stringify#12]
I received this error when dealing with a huge JSON.
**arguments**: object, null, 2

```sh
.../node_modules/safe-stable-stringify/stable.js:293
          res += tmp !== undefined ? tmp : 'null'
                                     ^

RangeError: Invalid string length
    at stringifyIndent (/home/home/workspaces/tesseract/node_modules/safe-stable-stringify/stable.js:293:38)
    at stringifyIndent (/home/home/workspaces/tesseract/node_modules/safe-stable-stringify/stable.js:322:21)
    at stringifyIndent (/home/home/workspaces/tesseract/node_modules/safe-stable-stringify/stable.js:322:21)
    at stringifyIndent (/home/home/workspaces/tesseract/node_modules/safe-stable-stringify/stable.js:292:23)
    at stringifyIndent (/home/home/workspaces/tesseract/node_modules/safe-stable-stringify/stable.js:322:21)
    at stringifyIndent (/home/home/workspaces/tesseract/node_modules/safe-stable-stringify/stable.js:292:23)
    at stringifyIndent (/home/home/workspaces/tesseract/node_modules/safe-stable-stringify/stable.js:322:21)
    at stringifyIndent (/home/home/workspaces/tesseract/node_modules/safe-stable-stringify/stable.js:296:21)
    at stringifyIndent (/home/home/workspaces/tesseract/node_modules/safe-stable-stringify/stable.js:322:21)
    at stringify (/home/home/workspaces/tesseract/node_modules/safe-stable-stringify/stable.js:592:14)
```

**Comment by BridgeAR** [comment]
@leodutra seems you reached the absolute maximum string size. That is currently ~2 ** 30 bytes for 64 bit systems and ~2 ** 28 bytes for 32 bit systems. The very same should also happen when using `JSON.stringify`.

You could try to use indent 1 instead of 2 or remove the formatting and see if that is sufficient but there's nothing that can be done here.

**Comment by leodutra** [comment]
I suspected of this possibility but I had to have some sleep, so I preferred to document it.
Thank you for the quick response.

**Comment by punkpeye** [comment]
Is there a way simply clip the value when this is happening instead of crashing the entire thing?

**Comment by BridgeAR** [comment]
I had a look into this and implementing this would either effect the performance quite a bit or it is kind of luck to not end up with a completely `redacted` output (removing everything that was already gathered). The reason is that the output has to stay JSON compatible and if a property in the middle causes this problem, all further additions are also going to cause the problem and nothing is left to actually show to the user in the end.

Do you have huge strings that are used as input? Those could be cut off with an option. There are also the `maximumBreadth` and `maximumDepth` options to achieve something similar.

It is not easy to address this fully due to being a hard limit in V8. You could report it to V8 since the limit is not defined in the spec. It would just require a lot of reports that this would be acted upon.

**Comment by BridgeAR** [comment]
The safe mode that will be published in the next version will be able to recover from this. The output is just more luck than anything deterministic in case the maximum string length is reached.
